#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint-fix || 
(
  echo "Linting failed. Please fix the errors and try again."
  false;
)

npm run lint || 
(
  echo "Linting failed. Please fix the errors and try again."
  false;
)

echo "All checks passed. Committing..."